# Generated by Django 3.1.2 on 2020-10-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='koder',
            old_name='full_name',
            new_name='name',
        ),
    ]
